<?xml version="1.0" encoding="utf-8"?><Database Name="SkyApi_db" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=i00kh6od4s.database.windows.net,1433;Initial Catalog=SkyApi_db;User ID=skyadmin@i00kh6od4s" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SkyApi_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Airport" Member="Airports">
    <Type Name="Airport">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FsCode" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Airport_Flight" Member="Flights" ThisKey="Id" OtherKey="SourceId" Type="Flight" />
      <Association Name="Airport_Flight1" Member="Flights1" ThisKey="Id" OtherKey="TargetId" Type="Flight" />
    </Type>
  </Table>
  <Table Name="dbo.Flight" Member="Flights">
    <Type Name="Flight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Start" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="[End]" Member="End" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SourceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TargetId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Flight_Flightmember" Member="Flightmembers" ThisKey="Id" OtherKey="FlightId" Type="Flightmember" />
      <Association Name="Airport_Flight" Member="Airport" ThisKey="SourceId" OtherKey="Id" Type="Airport" IsForeignKey="true" />
      <Association Name="Airport_Flight1" Member="Airport1" ThisKey="TargetId" OtherKey="Id" Type="Airport" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Flightmembers" Member="Flightmembers">
    <Type Name="Flightmember">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FlightId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Flight_Flightmember" Member="Flight" ThisKey="FlightId" OtherKey="Id" Type="Flight" IsForeignKey="true" />
      <Association Name="User_Flightmember" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="User_Flightmember" Member="Flightmembers" ThisKey="Id" OtherKey="UserId" Type="Flightmember" />
    </Type>
  </Table>
</Database>